version: '3'
services:
  backend:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=${PORT}
      - APP_URL=${APP_URL}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"